name: withtone
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.8.0
  lottie: any
  google_mobile_ads: ^3.0.0
  app_tracking_transparency: ^2.0.4
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  flutter_riverpod: ^2.4.9 # riverpod で状態管理する
  riverpod_annotation: ^2.3.3 # generator を使うために必要なアノテーション
  freezed_annotation: ^2.4.1 # freezed を使うために必要なアノテーション
  json_annotation: ^4.8.1 # json_serializable を使うために必要なアノテーション
  cloud_firestore: ^4.13.3
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6 # コード生成ツール
  riverpod_generator: ^2.3.9 # annotation から provider を生成するツール
  freezed: ^2.4.5 # annotation から immutable な class を生成するツール
  json_serializable: ^6.7.1 # annotation から class の json serialize/deserialize を生成するツール



flutter:

  uses-material-design: true

  assets:
  - assets/page_images/Intro.png
  - assets/page_images/learning community search.png
  - assets/page_images/login.png
  - assets/page_images/signup.png
  - assets/page_images/パスワード再発行ページ.jpg
  - assets/page_images/パスワード再発行確認ページ.jpg
  - assets/page_images/content.png
  - assets/page_images/upload_commentq.jpg
  - assets/page_images/upload_fb.jpg
  - assets/page_images/upload_inst.jpg
  - assets/page_images/upload_thankyouq.jpg
  - assets/page_images/upload_videoq.jpg
  - assets/page_images/profile_icon.png

  - assets/page_images/article.png
  - assets/page_images/professional.png
  - assets/page_images/profile.png
  - assets/page_images/search.png
  - assets/page_images/learning community home.png
  - assets/page_images/question.png
  - assets/page_images/feedback_line.png
  - assets/page_images/upload_videof.jpg
  - assets/page_images/upload_thankyouf.jpg
  - assets/page_images/feedback_video.png
  - assets/page_images/feedback.png
  - assets/page_images/settings.png
  - assets/page_images/notifications.png

  - assets/logo/app_nobackground.png
  - assets/logo/apple.png
  - assets/logo/appmain_color.png
  - assets/logo/facebook.png
  - assets/logo/google.png
  - assets/logo/mail.png
  - assets/logo/twitter.png
  - assets/logo/mainlogo.png
  - assets/logo/animelogo.json
  - assets/logo/Effects_Illustration.png
  - assets/logo/Upload_Illustration.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
